# Numpy

کتابخانه‌ی نامپای، کتابخانه‌ایست برای کار با داده‌های ماتریسی که عموماً حجم بالایی دارند و محاسبات آن‌ها مبتنی بر جبرخطی انجام می‌شود

In [6]:
import numpy as np

In [ ]:
vector = [1, 2, 3]  #لیست

In [3]:
print(type(vector))

<class 'list'>


In [4]:
nvector = numpy.array(vector)

In [5]:
nvector.shape

(3,)

In [6]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [7]:
nmatrix = numpy.array(matrix)

In [8]:
nmatrix.shape

(3, 3)

In [20]:
j = 3 #Scalar
i = [1, 2, 3] #vector
k = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
] #marix
x = [
    [[1, 2, 3], [6, 2, 3 ], [8, 4, 2], [8, 4, 2]], #matrix
    [[5, 2, 3], [6, 2, 3 ], [8, 4, 2], [8, 4, 2]],#matrix
    [[1, 7, 3], [6, 2, 3 ], [8, 4, 2], [8, 4, 2]],#matrix
    [[1, 7, 3], [6, 2, 3 ], [8, 4, 2], [8, 4, 2]]#matrix

] #tensor

In [21]:
temp = np.array(x)
temp.shape

(4, 4, 3)

In [22]:

narr = numpy.array([1, 2, 3])
narr

array([1, 2, 3])

In [ ]:
numpy.resize(narr, (4, 4)) # اگه عدد کم بیاره همونایی که هستو تکرار میکنه 

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [ ]:
narr.resize((3, 3), refcheck=False) #فرق این با بالایی اینه که تغیر روی خود ارایه اصلی ذخیره میشه
#اگه عدد کم بیار صفر میزاره

In [26]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
matrix = numpy.ones((5, 4))

In [28]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
matrix = numpy.zeros((4, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
numpy.diag(narr) #برگردوندن قطر اصلی ماتریس

array([1, 0, 0])

In [32]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [34]:
m1 = numpy.ones((4, 5), int)
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
m2 = numpy.zeros((4, 5), float)
m2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
numpy.vstack([m1, m2]) # دوتا ارایه رو روی هم میزاره (جمع نیست)   

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
numpy.hstack([m1, m2]) 

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

In [ ]:
[1, 2, 3] * [4, 5, 5] #ارایه های پایتونی رو نمیشه باهم ضرب کرد برای اینکار میبریم تو فضای جبر خطی

TypeError: can't multiply sequence by non-int of type 'list'

In [41]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 5])

In [42]:
z = x * y
z #حالا ماتریس ها در هم ضرب میشن

array([ 4, 10, 15])

In [43]:
x ** 2 

array([1, 4, 9])

In [ ]:
x.dot(y) #ضرب داخلی در بردار ها که نتیجه یک عدده

np.int64(29)

In [45]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
narr.T #ماتریس ترانهاده (جای سطر ها و ستون ها عوض شد)

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [47]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [31]:
narr.sum()

6

In [32]:
narr.max()

3

In [33]:
narr.min()

0

In [ ]:
narr.argmax() #ایندکس

2

In [35]:
narr.argmin()

3

In [36]:
narr.mean()

0.6666666666666666

In [37]:
narr.std()

1.0540925533894598

In [1]:
import numpy
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [39]:
mr[-6:14:2]

array([ 81, 121, 169], dtype=int32)

In [40]:
mr[5:-1:-1]

array([], dtype=int32)

In [41]:
mr[2]

4

In [42]:
mr[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [43]:
mr[:5]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [44]:
mr[-2:]

array([169, 196], dtype=int32)

In [46]:
mr[5:12:3]

array([ 25,  64, 121], dtype=int32)

In [45]:
mr[10::-2]

array([100,  64,  36,  16,   4,   0], dtype=int32)

In [47]:
mr[-10:-2:2]

array([ 25,  49,  81, 121], dtype=int32)

In [48]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [2]:
narr = numpy.array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
narr[-2::1, 1:3]

array([[0, 0],
       [0, 0]])

In [8]:
narr[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [ ]:
narr[::2, -1] #اینجا چون یک ستون انتخاب کردیم کلا یک ارایه برگردوند

array([3, 0])

In [11]:
narr[::2, -1:]

array([[3],
       [0]])

In [ ]:
narr[::-1, 2:] # با کاما ابعدا رو جدا میکنیم 
#اینجا دو بعدیه قبل کاما روی ردیف ها و بعد کاما روی ستون های ماتریس پیمایش میکنیم

array([[0],
       [0],
       [3]])

In [ ]:
narr[narr >= 0] # فیلتر کردن

array([1, 2, 3, 0, 0, 0, 0, 0, 0])

In [ ]:
narr[: , 0] #گرفتن ستون مورد نظر 
#narr[0] گرفتن سطر مورد نظر

array([1, 0, 0])

In [24]:
narr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [25]:
marr = narr[-1]
marr

array([0, 0, 0])

In [28]:
marr[:] = 1
marr

array([1, 1, 1])

In [ ]:
marr[:2] = 2 #اینجا یه بعد بیشتر نداریم اصلا
marr

array([2, 2, 1])

In [ ]:
narr #اینم تغیر کرده چون که اون چیزی که رفت روی ارایه ام ادرس همین متغیر بوده 

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [38]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [39]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
narr  #این بار چون کپی کردیم دیگه ادرس ها متفاوته و تغیرات اعمال نشد

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [87]:
tarr = numpy.random.randint(0, 10, (4, 3))
tarr

array([[9, 2, 4],
       [6, 0, 2],
       [3, 1, 8],
       [6, 2, 4]], dtype=int32)

In [94]:
tarr[3::3, 4:1:-2]

array([[4]], dtype=int32)

In [90]:
for r in tarr:
    r = r ** 2
    print(r)

[81  4 16]
[36  0  4]
[ 9  1 64]
[36  4 16]


In [ ]:
for i, r in enumerate(tarr): #تابعی که علاوه بر مقدار ایندکس اون رو هم میده
    print('index(' + str(i) + ') is ', r)

index(0) is  [9 2 4]
index(1) is  [6 0 2]
index(2) is  [3 1 8]
index(3) is  [6 2 4]


In [95]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [96]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [100]:
u = list(zip(narr, marr))
u

[(array([1, 2, 3]), array([0, 0, 0])),
 (array([0, 0, 0]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [101]:
arr = [1, 4, 2, 9, 8, 6, 3]
arr = numpy.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [102]:
len(arr) // 2

3

In [104]:
p = arr[len(arr) // 2]
p

np.int64(9)

In [107]:
l = [x for x in arr if x < p]
l

[np.int64(1), np.int64(4), np.int64(2), np.int64(8), np.int64(6), np.int64(3)]

In [76]:
r = [x for x in arr if x > p]
r

[]

In [77]:
m = [x for x in arr if x == p]
m

[9]

In [78]:
l + m + r

[1, 4, 2, 8, 6, 3, 9]

In [108]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr[len(arr) // 2]
    l = [x for x in arr if x  < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [ ]:
h = [3, 6, 4, 1, 3, 9, 4]
quicksort(h)

[np.int64(1),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(6),
 np.int64(9)]